name: Update Version

on:
  #push:
  #schedule:
  #  - cron: '0 */72 * * *'

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: 'sirredbeard/determined-bucket'

      - name: Update version
        run: |
          echo "Checking for new version..."
          LATEST_VERSION=$(curl --silent "https://api.github.com/repos/determined-ai/determined/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          echo "Checking current version..."
          CURRENT_VERSION=$(cat bucket/determined.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          echo "Latest version: $LATEST_VERSION"
          echo "Current version: $CURRENT_VERSION"

          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "Updating determined.json version to $LATEST_VERSION..."
            sed -i "s/$CURRENT_VERSION/$LATEST_VERSION/g" bucket/determined.json
            echo "Committing changes..."
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -am "Update determined version to $LATEST_VERSION"
            git push
            echo "Changes committed."
          else
            echo "No new version found."
          fi
